/*
 * System configuration.
 *
 * This file contains the settings for the chip's configuration bits.  This is
 * based on code generated from MCC.
 */

#ifndef __SYSCONFIG_H__
#define __SYSCONFIG_H__

// Set to 1 to connect the Slave core to the debug UART, or 0 to connect the
// Master core.
#define SLAVE_DEBUG_UART 0

#pragma config BWRP = OFF               // Boot Segment Write-Protect bit (Boot Segment may be written)
#pragma config BSS = DISABLED           // Boot Segment Code-Protect Level bits (No Protection (other than BWRP))
#pragma config BSEN = OFF               // Boot Segment Control bit (No Boot Segment)
#pragma config GWRP = OFF               // General Segment Write-Protect bit (General Segment may be written)
#pragma config GSS = DISABLED           // General Segment Code-Protect Level bits (No Protection (other than GWRP))
#pragma config CWRP = OFF               // Configuration Segment Write-Protect bit (Configuration Segment may be written)
#pragma config CSS = DISABLED           // Configuration Segment Code-Protect Level bits (No Protection (other than CWRP))
#pragma config AIVTDIS = OFF            // Alternate Interrupt Vector Table bit (Disabled AIVT)
#pragma config BSLIM = 0x1FFF           // Boot Segment Flash Page Address Limit bits (Boot Segment Flash page address  limit)
#pragma config FNOSC = 0x02             // Oscillator Source Selection (Primary Oscillator (external clock))
#pragma config IESO = OFF               // Two-speed Oscillator Start-up Enable bit (Start up with user-selected oscillator source)
#pragma config POSCMD = 0x00            // Primary Oscillator Mode Select bits (Primary oscillator enabled as EC)
#pragma config OSCIOFNC = ON            // OSC2 Pin Function bit (OSC2 is general purpose digital I/O pin)
#pragma config FCKSM = CSECMD           // Clock Switching Mode bits (Clock switching is enabled,Fail-safe Clock Monitor is disabled)
#pragma config XTCFG = G1               // XT Config (8-16 MHz crystals)
#pragma config XTBST = ENABLE           // XT Boost (Boost the kick-start)
#pragma config RWDTPS = PS1048576       // Run Mode Watchdog Timer Post Scaler select bits (1:1048576)
#pragma config RCLKSEL = LPRC           // Watchdog Timer Clock Select bits (Always use LPRC)
#pragma config WINDIS = ON              // Watchdog Timer Window Enable bit (Watchdog Timer operates in Non-Window mode)
#pragma config WDTWIN = WIN25           // Watchdog Timer Window Select bits (WDT Window is 25% of WDT period)
#pragma config SWDTPS = PS1048576       // Sleep Mode Watchdog Timer Post Scaler select bits (1:1048576)
#pragma config FWDTEN = ON_SW           // Watchdog Timer Enable bit (WDT controlled via SW, use WDTCON.ON bit)
#pragma config ICS = PGD2               // ICD Communication Channel Select bits (Communicate on PGEC2 and PGED2)
#pragma config JTAGEN = OFF             // JTAG Enable bit (JTAG is disabled)
#pragma config DMTIVTL = 0xFFFF         // Dead Man Timer Interval low word (Lower 16 bits of 32 bitDMT window interval (0-0xFFFF))
#pragma config DMTIVTH = 0xFFFF         // Dead Man Timer Interval high word (Uper 16 bits of 32 bitDMT window interval (0-0xFFFF))
#pragma config DMTCNTL = 0xFFFF         // Lower 16 bits of 32 bit DMT instruction count time-out value (0-0xFFFF) (Lower 16 bits of 32 bit DMT instruction count time-out value (0-0xFFFF))
#pragma config DMTCNTH = 0xFFFF         // Upper 16 bits of 32 bit DMT instruction count time-out value (0-0xFFFF) (Upper 16 bits of 32 bit DMT instruction count time-out value (0-0xFFFF))
#pragma config DMTDIS = OFF             // Dead Man Timer Disable bit (Dead Man Timer is Disabled and can be enabled by software)
#pragma config ALTI2C1 = OFF            // Alternate I2C1 Pin bit (I2C1 mapped to SDA1/SCL1 pins)
#pragma config ALTI2C2 = OFF            // Alternate I2C2 Pin bit (I2C2 mapped to SDA2/SCL2 pins)
#pragma config SMBEN = SMBUS            // SM Bus Enable (SMBus input threshold is enabled)
#pragma config SPI2PIN = DEDICATED      // SPI2 uses dedicated I/O pins
#pragma config CTXT1 = OFF              // Specifies Interrupt Priority Level (IPL) Associated to Alternate Working Register 1 bits (Not Assigned)
#pragma config CTXT2 = OFF              // Specifies Interrupt Priority Level (IPL) Associated to Alternate Working Register 2 bits (Not Assigned)
#pragma config CTXT3 = OFF              // Specifies Interrupt Priority Level (IPL) Associated to Alternate Working Register 3 bits (Not Assigned)
#pragma config CTXT4 = OFF              // Specifies Interrupt Priority Level (IPL) Associated to Alternate Working Register 4 bits (Not Assigned)
#pragma config MBXM0 = S2M              // Mailbox 0 data direction (Mailbox register configured for Master data read (Slave to Master data transfer))
#pragma config MBXM1 = S2M              // Mailbox 1 data direction (Mailbox register configured for Master data read (Slave to Master data transfer))
#pragma config MBXM2 = M2S              // Mailbox 2 data direction (Mailbox register configured for Master data write (Master to Slave data transfer))
#pragma config MBXM3 = S2M              // Mailbox 3 data direction (Mailbox register configured for Master data read (Slave to Master data transfer))
#pragma config MBXM4 = S2M              // Mailbox 4 data direction (Mailbox register configured for Master data read (Slave to Master data transfer))
#pragma config MBXM5 = S2M              // Mailbox 5 data direction (Mailbox register configured for Master data read (Slave to Master data transfer))
#pragma config MBXM6 = S2M              // Mailbox 6 data direction (Mailbox register configured for Master data read (Slave to Master data transfer))
#pragma config MBXM7 = S2M              // Mailbox 7 data direction (Mailbox register configured for Master data read (Slave to Master data transfer))
#pragma config MBXM8 = S2M              // Mailbox 8 data direction (Mailbox register configured for Master data read (Slave to Master data transfer))
#pragma config MBXM9 = S2M              // Mailbox 9 data direction (Mailbox register configured for Master data read (Slave to Master data transfer))
#pragma config MBXM10 = S2M             // Mailbox 10 data direction (Mailbox register configured for Master data read (Slave to Master data transfer))
#pragma config MBXM11 = S2M             // Mailbox 11 data direction (Mailbox register configured for Master data read (Slave to Master data transfer))
#pragma config MBXM12 = S2M             // Mailbox 12 data direction (Mailbox register configured for Master data read (Slave to Master data transfer))
#pragma config MBXM13 = S2M             // Mailbox 13 data direction (Mailbox register configured for Master data read (Slave to Master data transfer))
#pragma config MBXM14 = S2M             // Mailbox 14 data direction (Mailbox register configured for Master data read (Slave to Master data transfer))
#pragma config MBXM15 = S2M             // Mailbox 15 data direction (Mailbox register configured for Master data read (Slave to Master data transfer))

#pragma config MBXHSA = MBX0            // Mailbox handshake protocol block A register assignment (MSIxMBXD0 assigned to mailbox handshake protocol block A)
#pragma config MBXHSB = MBX1            // Mailbox handshake protocol block B register assignment (MSIxMBXD1 assigned to mailbox handshake protocol block B)
#pragma config MBXHSC = MBX2            // Mailbox handshake protocol block C register assignment (MSIxMBXD15 assigned to mailbox handshake protocol block C)
#pragma config MBXHSD = MBX15           // Mailbox handshake protocol block D register assignment (MSIxMBXD15 assigned to mailbox handshake protocol block D)
#pragma config MBXHSE = MBX15           // Mailbox handshake protocol block E register assignment (MSIxMBXD15 assigned to mailbox handshake protocol block E)
#pragma config MBXHSF = MBX15           // Mailbox handshake protocol block F register assignment (MSIxMBXD15 assigned to mailbox handshake protocol block F)
#pragma config MBXHSG = MBX15           // Mailbox handshake protocol block G register assignment (MSIxMBXD15 assigned to mailbox handshake protocol block G)
#pragma config MBXHSH = MBX15           // Mailbox handshake protocol block H register assignment (MSIxMBXD15 assigned to mailbox handshake protocol block H)

#pragma config HSAEN = ON              // Mailbox A data flow control protocol block enable (Mailbox data flow control handshake protocol block enabled.)
#pragma config HSBEN = ON              // Mailbox B data flow control protocol block enable (Mailbox data flow control handshake protocol block enabled.)
#pragma config HSCEN = ON              // Mailbox C data flow control protocol block enable (Mailbox data flow control handshake protocol block enabled.)
#pragma config HSDEN = OFF              // Mailbox D data flow control protocol block enable (Mailbox data flow control handshake protocol block disabled.)
#pragma config HSEEN = OFF              // Mailbox E data flow control protocol block enable (Mailbox data flow control handshake protocol block disabled.)
#pragma config HSFEN = OFF              // Mailbox F data flow control protocol block enable (Mailbox data flow control handshake protocol block disabled.)
#pragma config HSGEN = OFF              // Mailbox G data flow control protocol block enable (Mailbox data flow control handshake protocol block disabled.)
#pragma config HSHEN = OFF              // Mailbox H data flow control protocol block enable (Mailbox data flow control handshake protocol block disabled.)

#pragma config CPRA0 = MSTR             // Pin RA0 Ownership Bits (Master core owns pin.)
#pragma config CPRA1 = MSTR             // Pin RA1 Ownership Bits (Master core owns pin.)
#pragma config CPRA2 = MSTR             // Pin RA2 Ownership Bits (Master core owns pin.)
#pragma config CPRA3 = MSTR             // Pin RA3 Ownership Bits (Master core owns pin.)
#pragma config CPRA4 = MSTR             // Pin RA4 Ownership Bits (Master core owns pin.)

#pragma config CPRB0 = MSTR             // Pin RB0 Ownership Bits (Master core owns pin.)
#pragma config CPRB1 = MSTR             // Pin RB1 Ownership Bits (Master core owns pin.)
#pragma config CPRB2 = SLV1             // Pin RB2 Ownership Bits (Slave core owns pin.)
#pragma config CPRB3 = MSTR             // Pin RB3 Ownership Bits (Master core owns pin.)
#pragma config CPRB4 = MSTR             // Pin RB4 Ownership Bits (Master core owns pin.)
#pragma config CPRB5 = MSTR             // Pin RB5 Ownership Bits (Master core owns pin.)
#pragma config CPRB6 = MSTR             // Pin RB6 Ownership Bits (Master core owns pin.)
#pragma config CPRB7 = MSTR             // Pin RB7 Ownership Bits (Master core owns pin.)
#pragma config CPRB8 = MSTR             // Pin RB8 Ownership Bits (Master core owns pin.)
#pragma config CPRB9 = MSTR             // Pin RB9 Ownership Bits (Master core owns pin.)
#pragma config CPRB10 = MSTR            // Pin RB10 Ownership Bits (Master core owns pin.)
#pragma config CPRB11 = MSTR            // Pin RB11 Ownership Bits (Master core owns pin.)
#pragma config CPRB12 = MSTR            // Pin RB12 Ownership Bits (Master core owns pin.)
#pragma config CPRB13 = MSTR            // Pin RB13 Ownership Bits (Master core owns pin.)
#pragma config CPRB14 = MSTR            // Pin RB14 Ownership Bits (Master core owns pin.)
#pragma config CPRB15 = MSTR            // Pin RB15 Ownership Bits (Master core owns pin.)

#pragma config CPRC0 = MSTR             // Pin RC0 Ownership Bits (Master core owns pin.)
#pragma config CPRC1 = MSTR             // Pin RC1 Ownership Bits (Master core owns pin.)
#pragma config CPRC2 = MSTR             // Pin RC2 Ownership Bits (Master core owns pin.)
#pragma config CPRC3 = MSTR             // Pin RC3 Ownership Bits (Master core owns pin.)
#pragma config CPRC4 = MSTR             // Pin RC4 Ownership Bits (Master core owns pin.)
#pragma config CPRC5 = SLV1             // Pin RC5 Ownership Bits (Slave 1 core owns pin.)
#pragma config CPRC6 = MSTR             // Pin RC6 Ownership Bits (Master core owns pin.)
#pragma config CPRC7 = MSTR             // Pin RC7 Ownership Bits (Master core owns pin.)
#pragma config CPRC8 = MSTR             // Pin RC8 Ownership Bits (Master core owns pin.)
#pragma config CPRC9 = MSTR             // Pin RC9 Ownership Bits (Master core owns pin.)
#pragma config CPRC10 = MSTR            // Pin RC10 Ownership Bits (Master core owns pin.)
//#pragma config CPRC11 = MSTR            // Pin RC11 Ownership Bits (Master core owns pin.)
#pragma config CPRC12 = MSTR            // Pin RC12 Ownership Bits (Master core owns pin.)
#pragma config CPRC13 = SLV1            // Pin RC13 Ownership Bits (Slave 1 core owns pin.)
#pragma config CPRC14 = SLV1            // Pin RC14 Ownership Bits (Slave 1 core owns pin.)
#pragma config CPRC15 = MSTR            // Pin RC15 Ownership Bits (Master core owns pin.)

// Use the SLAVE_DEBUG_UART to select which device can write to the UART TX pin
#if SLAVE_DEBUG_UART == 1
#pragma config CPRC11 = SLV1             // Pin RC11 Ownership Bits (Slave core owns pin.)
#else
#pragma config CPRC11 = MSTR             // Pin RC11 Ownership Bits (Master core owns pin.)
#endif

#pragma config CPRD0 = MSTR             // Pin RD0 Ownership Bits (Master core owns pin.)
#pragma config CPRD1 = MSTR             // Pin RD2 Ownership Bits (Master core owns pin.)
#pragma config CPRD2 = MSTR             // Pin RD2 Ownership Bits (Master core owns pin.)
#pragma config CPRD3 = MSTR             // Pin RD3 Ownership Bits (Master core owns pin.)
#pragma config CPRD4 = MSTR             // Pin RD4 Ownership Bits (Master core owns pin.)
#pragma config CPRD5 = MSTR             // Pin RD5 Ownership Bits (Master core owns pin.)
#pragma config CPRD6 = MSTR             // Pin RD6 Ownership Bits (Master core owns pin.)
#pragma config CPRD7 = MSTR             // Pin RD7 Ownership Bits (Master core owns pin.)
#pragma config CPRD8 = MSTR             // Pin RD8 Ownership Bits (Master core owns pin.)
#pragma config CPRD9 = SLV1             // Pin RD9 Ownership Bits (Slave 1 core owns pin.)
#pragma config CPRD10 = SLV1            // Pin RD10 Ownership Bits (Slave 1 core owns pin.)
#pragma config CPRD11 = MSTR            // Pin RD11 Ownership Bits (Master core owns pin.)
#pragma config CPRD12 = MSTR            // Pin RD12 Ownership Bits (Master core owns pin.)
#pragma config CPRD13 = MSTR            // Pin RD13 Ownership Bits (Master core owns pin.)
#pragma config CPRD14 = MSTR            // Pin RD14 Ownership Bits (Master core owns pin.)
#pragma config CPRD15 = MSTR            // Pin RD15 Ownership Bits (Master core owns pin.)

#pragma config CPRE0 = MSTR             // Pin RE0 Ownership Bits (Master core owns pin.)
#pragma config CPRE1 = SLV1             // Pin RE1 Ownership Bits (Slave 1 core owns pin.)
#pragma config CPRE2 = MSTR             // Pin RE2 Ownership Bits (Master core owns pin.)
#pragma config CPRE3 = MSTR             // Pin RE3 Ownership Bits (Master core owns pin.)
#pragma config CPRE4 = MSTR             // Pin RE4 Ownership Bits (Master core owns pin.)
#pragma config CPRE5 = MSTR             // Pin RE5 Ownership Bits (Master core owns pin.)
#pragma config CPRE6 = MSTR             // Pin RE6 Ownership Bits (Master core owns pin.)
#pragma config CPRE7 = SLV1             // Pin RE7 Ownership Bits (Slave 1 core owns pin.)
#pragma config CPRE8 = MSTR             // Pin RE8 Ownership Bits (Master core owns pin.)
#pragma config CPRE9 = MSTR             // Pin RE9 Ownership Bits (Master core owns pin.)
#pragma config CPRE10 = MSTR            // Pin RE10 Ownership Bits (Master core owns pin.)
#pragma config CPRE11 = MSTR            // Pin RE11 Ownership Bits (Master core owns pin.)
#pragma config CPRE12 = MSTR            // Pin RE12 Ownership Bits (Master core owns pin.)
#pragma config CPRE13 = MSTR            // Pin RE13 Ownership Bits (Master core owns pin.)
#pragma config CPRE14 = MSTR            // Pin RE14 Ownership Bits (Master core owns pin.)
#pragma config CPRE15 = MSTR            // Pin RE15 Ownership Bits (Master core owns pin.)

#pragma config S1FNOSC = 0x02           // Oscillator Source Selection (Internal Fast RC (FRC))
#pragma config S1IESO = OFF             // Two-speed Oscillator Start-up Enable bit (Start up with user-selected oscillator source)
#pragma config S1OSCIOFNC = ON          // Slave OSC2 Pin Function bit (OSC2 is general purpose digital I/O pin)
#pragma config S1FCKSM = CSECMD         // Clock Switching Mode bits (Clock switching is enabled,Fail-safe Clock Monitor is disabled)
#pragma config S1RWDTPS = PS1048576     // Run Mode Watchdog Timer Post Scaler select bits (1:1048576)
#pragma config S1RCLKSEL = LPRC         // Watchdog Timer Clock Select bits (Always use LPRC)
#pragma config S1WINDIS = ON            // Watchdog Timer Window Enable bit (Watchdog Timer operates in Non-Window mode)
#pragma config S1WDTWIN = WIN25         // Watchdog Timer Window Select bits (WDT Window is 25% of WDT period)
#pragma config S1SWDTPS = PS1048576     // Sleep Mode Watchdog Timer Post Scaler select bits (1:1048576)
#pragma config S1FWDTEN = ON_SW         // Watchdog Timer Enable bit (WDT controlled via WDTCON.ON bit)

//Note: On the dsPIC33CH Curiosity Development Board, when performing single debug of the slave only, the debug connection is made to the slave through RB3/S1PGD2 and RB4/S1PGC2.
//However, when performing dual debug of both the master and slave simultaneously, the RB3/RB4 pins are used for debugging the master, and the slave must therefore use
//the dedicated slave debug port (header J15 on the board), which is connected to RB5/S1PGD3 and RB6/S1PGC3
#pragma config S1ICS = PGD2             // ICD Communication Channel Select bits (Communicate on S1PGEC2 and S1PGED2)
//#pragma config S1ICS = PGD3             // ICD Communication Channel Select bits (Communicate on S1PGEC3 and S1PGED3)

#pragma config S1ISOLAT = ON            // Isolate the Slave core subsystem from the master subsystem during Debug (The slave can operate (in debug mode) even if the SLVEN bit in the MSI is zero.)
#pragma config S1NOBTSWP = OFF          // BOOTSWP Instruction Enable/Disable bit (BOOTSWP instruction is disabled)
#pragma config S1ALTI2C1 = OFF          // Alternate I2C1 Pin bit (I2C1 mapped to SDA1/SCL1 pins)
#pragma config S1SPI1PIN = PPS          // S1 SPI1 Pin Select bit (Slave SPI1 uses I/O remap (PPS) pins)
#pragma config S1SSRE = ON              // Slave Slave Reset Enable (Slave generated resets will reset the Slave Enable Bit in the MSI module)
#pragma config S1MSRE = ON              // Master Slave Reset Enable (The master software oriented RESET events (RESET Op-Code, Watchdog timeout, TRAP reset, illegalInstruction) will also cause the slave subsystem to reset.)
#pragma config S1CTXT1 = IPL6            // Specifies Interrupt Priority Level (IPL) Associated to Alternate Working Register 1 bits (IPL6)
#pragma config S1CTXT2 = OFF            // Specifies Interrupt Priority Level (IPL) Associated to Alternate Working Register 2 bits (Not Assigned)
#pragma config S1CTXT3 = OFF            // Specifies Interrupt Priority Level (IPL) Associated to Alternate Working Register 3 bits (Not Assigned)
#pragma config S1CTXT4 = OFF            // Specifies Interrupt Priority Level (IPL) Associated to Alternate Working Register 4 bits (Not Assigned)

#endif
